### ISSUE TITLE
cron-Job of nextcloud server fails with TypeError : stream_get_contents() expects parameter 1 to be resource, bool given in /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php:173

### ISSUE THREAD

**Issue by kinimoas** [nextcloud/documentserver_community#245]
I get the following error on the cron-job twice a day

```
TypeError: stream_get_contents() expects parameter 1 to be resource, bool given in /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php:173
Stack trace:
#0 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php(173): stream_get_contents()
#1 /var/www/html/nextcloud/apps/documentserver_community/lib/LocalAppData.php(102): OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}()
#2 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php(176): OCA\DocumentServer\LocalAppData->getReadWriteLocalPath()
#3 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php(58): OCA\DocumentServer\Document\DocumentStore->saveChanges()
#4 /var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php(71): OCA\DocumentServer\Document\SaveHandler->flushChanges()
#5 /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php(79): OCA\DocumentServer\BackgroundJob\Cleanup->run()
#6 /var/www/html/nextcloud/cron.php(128): OCP\BackgroundJob\Job->execute()
#7 {main}
```

Nextcloud version Nextcloud Hub II (23.0.0)

Community Document Server 0.1.11

I'm aware that this version fo teh document server is not recomented for the newest version of nextcloud server.
Maybe this is useful anyway.

**Comment by kinimoas** [comment]
This only occurs twice a day

**Comment by igherardia** [comment]
same proble here

**Comment by adsche** [comment]
Digging into the source:

The method is called in DocumentStore.php, l. 173, with a variable `$savedContent` as parameter.
`$savedContent` is initialized in l. 158 of the same file with `fopen(...).
According to [php docs](https://www.php.net/manual/en/function.fopen.php), fopen "[r]eturns a file pointer resource on success, or false on failure".

So, apparently, opening a file fails but there is **no error handling** of the `fopen` call, even though filesystem calls fail relatively often. :( The error-return value `false` is just passed along and used instead of a stream.

**Comment by adsche** [comment]
In our case, the specific error was triggered because a file had been renamed by someone* while open for someone else, and the file extension changed (docx -> bak). However, the above mentioned code just assumes an extension and appends it to the file name without error checking. Not sure if changing the extension was relevant or if any renaming makes this fail.

*) because of https://github.com/nextcloud/documentserver_community/issues/12 and https://github.com/nextcloud/documentserver_community/issues/281

**Comment by adsche** [comment]
There's still no error handling on the fopen() call, so this bug is still easily triggered by renaming files.

https://github.com/nextcloud/documentserver_community/blob/d3fbf99169857f9d8fb77bf95e29ad7339342c25/lib/Document/DocumentStore.php#L158-L173

**Comment by c7b3rx** [comment]
I am also getting this error, NC 25.0.13 php 8.1

TypeError: stream_get_contents(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php:173
Stack trace:
#0 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php(173): stream_get_contents()
#1 /var/www/html/nextcloud/apps/documentserver_community/lib/LocalAppData.php(102): OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}()
#2 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php(176): OCA\DocumentServer\LocalAppData->getReadWriteLocalPath()
#3 /var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php(58): OCA\DocumentServer\Document\DocumentStore->saveChanges()
#4 /var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php(71): OCA\DocumentServer\Document\SaveHandler->flushChanges()
#5 /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\DocumentServer\BackgroundJob\Cleanup->run()
#6 /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php(64): OCP\BackgroundJob\Job->start()
#7 /var/www/html/nextcloud/cron.php(152): OCP\BackgroundJob\Job->execute()
#8 {main}
