### ISSUE TITLE
PDF prints are blank - Document Server cant print any fonts

### ISSUE THREAD

**Issue by templis** [nextcloud/documentserver_community#251]
If you try to print over the document server community the whole Document is empty or sometimes incomplete

I've allready tried to clear browser caches and also reinstalled the document server and onlyoffice

The Version of the document Server I run is: 0.1.12

**Comment by plaing1** [comment]
Hi guys,

I can confirm this one.
The print function is generating a PDF, before printing.
Have tried to download as PDF and the behavior is similar.
When exporting to PDF from an OnlyOffice spreadsheet or document, the text is missing. Formatting (e.g. cell background color, table borders) are preserved when exporting from Spreadsheets and images and the number of pages have been preserved when exporting a document.

This started after updating Community Document Server from 0.1.11 to 0.1.12
Nextcloud version 21.0.7

Your prompt assistance is appreciated.

**Comment by roru69** [comment]
Hi,

Same issue here. 

Nextcloud version 23.0.1 RC#
Community Document Server 0.1.12

**Comment by ostasevych** [comment]
I confirm, that PDF are blank. Additionally, I see that preview icons of the document files are also blank. Perhaps, these are interconnected issues?

![image](https://user-images.githubusercontent.com/5199030/155143768-f562abaa-68f9-4bff-954c-219b79d5c8be.png)

**Comment by Jackson90** [comment]
I can confirm exactly these problems as well. By the way, the same problems exist with download/export as HTML. 

Onlyoffice Document Editor 6.4.2
Community Document Server 0.1.12
Nextcloud Hub II 23.0.2

As a hint and tip: At least in my case, an S3 bucket is used as primary storage - and according to first looks into the logs, the local storage seems to be partially addressed during export.

**Comment by cyberopssn** [comment]
Same problem here with print error (blank page)

**Comment by kennyMC** [comment]
Same problem.
ONLYOFFICE connector 7.3.2
Community Document Server 0.1.12
Nextcloud Hub II (23.0.2)

**Comment by phaser32** [comment]
Good morning,
I have the same identical issue.
Nextcloud 23.0.3 + OnlyOffice 7.3.2
Searching on the web I found this info

[https://community.nethserver.org/t/onlyoffice-print-problem/18449/11]

But I don't know how to proceed... :(
May be could be helpful..
Regards
Ale

**Comment by igherardia** [comment]
Same issue please can help us

Regards
Ignacio

**Comment by igherardia** [comment]
Good morning,
I have the same identical issue.
Nextcloud 23.0.3 + OnlyOffice 7.3.2
any solution?

**Comment by igherardia** [comment]
I was able to manage to load some fonts using the following command with SNAP

sudo nextcloud.occ documentserver:fonts --add /snap/nextcloud/30258/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
the default source is in that path

sudo nextcloud.occ documentserver:fonts                      #This command show the install fonts on documen server
DejaVuSans-Bold.ttf
DejaVuSans.ttf
DejaVuSansMono-Bold.ttf
DejaVuSansMono.ttf

The problem is not solved
I change de Arial font in spreadsheet to dejavu but do the same no print visible

**Comment by latency0ms** [comment]
All users seem to be affected by this problem - when fix?

```
Community Document Server 0.1.12
ONLYOFFICE 7.3.4
Nextcloud 22.2.7
```

**Comment by weasam** [comment]
Nextcloud 23.0.4  problem still insist, this issue title should be change to 
       Onlyoffice Document server print PDF empty, 
        or 
        Onlyoffice Document server could not print fonts to PDF ,
Install a standalone only office server in a different domain name

**Comment by pizzidellamaremma** [comment]
I'm having the same issue with Nextcloud 24.0.3 and Onlyoffice Docs latest image on Docker, is there any news?

**Comment by arustler** [comment]
I had/have the same problem. I saw that my /usr/share/fonts folder was pretty empty. After I installing fonts on my server with `apt install fonts-* ttf-mscorefonts-installer` most fonts are beeing printed again but not all of them.

**Comment by Polytracker** [comment]
I was able to solve this  as per the above comment, In my case the Nextcloud container only had one font installed. I was able to exec into the nextcloud container and run the following commands:

`sudo apt-get update`
`apt-get install ttf-mscorefonts-installer`

note that for this to work you will need to make sure that contrib is added to your sources.

**Comment by phaser32** [comment]
Hi Polytracker,
thank You for reply.
By the way I didn't understand what You mean when You say:
"you will need to make sure that contrib is added to your sources."
Can You help me please?
Thx so much
Ale

**Comment by Polytracker** [comment]
@phaser32  have a look here: https://gist.github.com/ChristopherA/680b4eeeeb6e9e4c7fc59c010a23b6cd

**Comment by phaser32** [comment]
@Polytracker Thx again

**Comment by ostasevych** [comment]
I have checked with 24.0.6 and found that the issue has gone.

**Comment by phaser32** [comment]
@ostasevych Good morning, Your statement leaves me a little bit perplexed. How can You make work Document Server on 24.0.6 ? It is not compatible.
Please share info about it, I'm really interested.
Than You very much
Ale

**Comment by adi-dev** [comment]
I just want to drop in here that I have the same issue. Strangely, never noticed this before and don't know if this was working before upgrade to NC25.0.1. Tried to install some fonts and add them to the server, but no luck. Document server 0.1.13, Onlyoffice 7.6.8. Printing or downloading as PDF produces empty pages or just graphics, no fonts. Export to PDF/A just does nothing.

**Comment by phaser32** [comment]
I finally solved the problem scheduling a cron every minute like I wrote here:
`https://github.com/nextcloud/documentserver_community/issues/281`
SOLVED!!!
I hope this could help anyone who's got the same issue.
Regards
Ale

**Comment by mrbaseman** [comment]
same here, installing `ttf-mscorefonts-installer` didn't help, nextcloud 25.0.1,  Community Document Server
0.1.13, ONLYOFFICE 7.6.8, running on Ubuntu 18.04 LTS with ppa:ondrej/php entabled to get php 8.x support

**Comment by weasam** [comment]
Forget about Community Document Server apps in Nextcloud store, install OnlyOffice in docker much easier to fix those issue

**Comment by mrbaseman** [comment]
If you don't have a vm or a dedicated server you usually can't run a docker container at a web hosting provider. Even a vm may come with a preinstalled kernel that is stripped down to a minimum, so that containers won't work. I even suspect that some providers sell container instances under the flag of a hosted vm instance in the cheaper market segment

**Comment by mrbaseman** [comment]
after installing the `ttf-mscorefonts-installer` package on Ubuntu  I have tried to rebuild fonts `occ documentserver:fonts --rebuild` but ran into issue #278 in my local installation (on the hosted platform I wouldn't have the permissions to change anything in the software setup of the host)

**Comment by phaser32** [comment]
Hi mrbaseman, I'm working on a shared hosting and I launched the comand on OCC Web `documentserver:fonts --rebuild` without problem. After some second it display "Rebuilding" and apparently everything were executed correctly but same issue here. When I print a doc file eg. ... nothing blank paper :(

**Comment by mrbaseman** [comment]
unfortunately in my shared hosting environment (1&1) the occ command also failed with a segmentation fault 
Anyhow, the document server in combination with the onlyoffice environment is great, even if printing into a pdf is currently not working...

**Comment by komoricodrutz** [comment]
I am having the same problem with 25.0.7 with OnlyOffice Community Document Server 0.1.13 installed:

```
rebuilding
Segmentation fault

An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

```
Related to #257 
and probably to #278

**Comment by Axehaft** [comment]
I see there is little action on this issue/bug.  This makes NC unusable in any professional setting which might require PDF's or spreadsheets.  

If anybody knows of any work arounds at all, please let us know.  (I've tried adding fonts as per mentioned above, but no change.) Otherwise its back to Google Docs for me.

**Comment by cyfrax** [comment]
unfortunately not only unusable in a professional setup but unusable in any setup. Without PDFs it's quite hard to live nowadays :-) Especially as the print function works via PDF output which are blank.
I tested it with a public document server, same thing. So maybe this is more of an OnlyOffice problem? Or are all document servers affected?

**Comment by bornostojak** [comment]
Hi, I'm still seeing this issue on my Nextcloud installation

```
Community Document Server 0.1.18
ONLYOFFICE 9.5.0
Nextcloud 30.0.1
``` 

can you provide any update on this issue?

**Comment by AugustDeer** [comment]
Still encountering this issue.
```
Community Document Server 0.2.0
ONLYOFFICE 9.9.0
Nextcloud 30.0.12
```

**Comment by chadek** [comment]
I took a look into core dump, it appears that php ASC.ttf font is actually in a format that breaks the parser at some point. Deleting it or regenerating it solve that issue but it then leads to onlyoffice opening document with weird default indie character like font in my case. If someone have time to play with this and providing me some feedback on how it behave somewhere else it would be great: I don't really want to "broke" people's document display just fixing this issue like that. If someone would like to play around and suggest something, we could get rid of this loooong standing issue.

**Comment by Nesh108** [comment]
Years later and still not touched, is anyone even looking at this?

**Comment by chadek** [comment]
Fixed for **v0.4.0**, by #402. Your title named it exactly — "Document Server cant print any fonts" — four years before anybody worked out why, and clearing caches and reinstalling could not have helped, because the broken state was shipped in the archive itself.

**What it was.** `server/FileConverter/bin/font_selection.bin` stores an **absolute** path to every bundled font, written by whichever machine ran `allfontsgen` — the build machine, for an app store install. When one of those paths does not resolve on the machine that is running, x2t's PDF writer prints `Can't load fontfile` on **stdout**, writes a PDF with no glyphs in it, and **exits 0**. Nothing was logged and nothing was thrown, so from everywhere else in the system a blank PDF and a good one were the same successful conversion. That is why this stood for four years: there was no failure to find.

Same input, same binary, same exit code:

| `font_selection.bin` holds | x2t exit | PDF size | text characters |
| --- | --- | --- | --- |
| paths that do not resolve here | 0 | 1 937 B | **0** |
| paths pinned to `../../../core-fonts/` | 0 | 12 804 B | the text that went in |

The build already pinned `AllFonts.js` to paths relative to x2t's working directory and deliberately left `font_selection.bin` alone, on a belief written into the Makefile: that its paths *"are not used for loading"*. They are not used by the change-replay path that comment is about, which reads `AllFonts.js`. They are used by the PDF writer.

**What changed** (#402):

* **The paths are pinned relative at build time**, so one machine's layout is no longer shipped to everybody. x2t accepts relative paths in `font_selection.bin` — verified first, since `AllFonts.js` accepting them does not prove it. The file is not `sed`-able (its strings are length-prefixed with a little-endian int32, so replacing one without fixing its prefix corrupts everything after it), so the rewriter is a real one, shared between the build and the runtime rebuild so both produce the same thing. Custom fonts live in appdata, outside the app directory, and keep the absolute paths they are found at.
* **A font rebuild that does not rebuild now says so.** The old check accepted *any* `AllFonts.js` containing `/core-fonts/` — including a stale one left over from the build — so a rebuild that wrote nothing at all reported success, and it never looked at `font_selection.bin` at all. It now verifies that this run wrote both files, that the write succeeded, and that every pinned path resolves; and it refuses up front, naming the file and the user, when it cannot write. That case is the shape of #145 and #278, each of which left the user with blank PDFs and no diagnostic.
* **The failure is visible now.** x2t's stdout is scanned for `Can't load fontfile` and logged, rather than discarding the one stream that mentioned it. `occ documentserver:fonts` also returned 1 on success and 0 on failure, so anything scripting it was told the opposite of what happened.

**Proof.** `tests/rig/pdf_test.py` is new — the rig had no PDF coverage at all, which is exactly why this survived. It asserts on extracted text rather than file size. Run against `master` just now, Nextcloud 34, ONLYOFFICE connector 10.1, bundled Euro-Office 9.3.4:

```
== a converted PDF has the text in it
   ok - "PdfFontProbe" is in the 12859 byte PDF
== a font path that does not resolve reaches the log
   ok - logged, and the PDF came out blank as expected
== a font rebuild that cannot write says so
   ok - exit 1, and it named the file

   VERDICT: conversion=ok reported=ok rebuild=ok
-- pdf: PASS in 6s
```

The second case deliberately breaks a font path and checks that the blank PDF is now *reported*, so the silent-failure half cannot come back either. It was confirmed to fail against the pre-fix font file (`FAIL - "PdfFontProbe" is not in the 1937 byte PDF`).

This ships in **v0.4.0**, and the test runs in CI on pull requests and weekly.
