### ISSUE TITLE
"OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned.

### ISSUE THREAD

**Issue by taschenlampe** [nextcloud/documentserver_community#296]
Hi all!

I see this while  the maintenance:repair command runs

```
- Rebuild font library
     - WARNING: Error while trying to rebuild fonts, if you had any custom fonts configured you'll need to run `occ documentserver:fonts --rebuild`
```

 ```
sudo -u www-data php /var/www/nextcloud/occ documentserver:fonts --rebuild
rebuilding
Segmentation fault

An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('...')
#7 {main}⏎ 
```

NC: 26.0
OS: "Ubuntu 22.04.2 LTS"

What would you suggest I´d do?
Peace!

**Comment by komoricodrutz** [comment]
Same issue here, on NC27.0 / TurnkeyLinux Nextcloud, Debian 11.7:

`rebuilding
Segmentation fault

An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('...')
#7 {main}`

Can anyone help?

**Comment by Adi-18** [comment]
Same here on Debian GNU/Linux 10 (buster) and NC27.0

**Comment by S0me6uy** [comment]
Hello,

Same for me with exactly same log

**Comment by zazo80** [comment]
Hi,
Same here, Ubunt 20.04 NC 27.0.2

root@dms:/var/www/nextcloud# sudo -u www-data php occ documentserver:fonts --rebuild                                                             rebuilding
Segmentation fault (core dumped)

An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('...')

**Comment by komoricodrutz** [comment]
Adding info so the bug doesn't get closed for inactivity.
3 months later and my 2 NC server instances have been updated to 27.1.1 / 25.0.12
Issue is still the same.
Also tried adding some fonts manually with the **occ documentserver:fonts --add** command and the fonts seem to be added, but then during the rebuild, I get the same error.
Once added, the command **occ documentserver:fonts** lists the installed fonts but then immediately proceeds with spitting out the exact same error and if you try to print the documents, they still show up blank.
I also built a third NC Server from scratch, which is also 27.1.1 now and the issue is exactly the same.
Related issues #278 and #251 also see no progress. I also found several other related issues, even older than these, but nobody seems to be able to come up with a workable solution.

**Comment by janisstreib** [comment]
Same here.
The segfault seems to happen in `apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/tools/allfontsgen` executed in `apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin`.
The binary seems to originate from [the ONYOFFICE project]( https://github.com/ONLYOFFICE/core/tree/83fc19672df4960b9c9ad013824cbfe462302fde/DesktopEditor/AllFontsGen).

I've tried Manually updating the files from their latest release but the segafult seems to persist. According to `dmesg` , the segfault happens in `libgraphics.so` .

**Comment by cernst72** [comment]
Same here using the official docker image nextcloud:28.0.1-apache
```
$ docker exec -u www-data $(docker ps -q -f name=cl_cloud.1) php occ  documentserver:fonts -v
No fonts added
An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/html/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\DocumentServer\Command\Fonts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/console.php(100): OC\Console\Application->run()
#6 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by VodyakovDenis** [comment]
This also happens on 28.0.2 version
```bash
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('...')
```

**Comment by TPSONLINE-INFO** [comment]
Hello got the same here
NC7 28.0.2
Any idea?

**Comment by floot** [comment]
Same on 28.0.5, issue being more than 1 year old now...
At least, is there any workaround to this?
What are the impacts of this failure with ONLYOFFICE usage?

**Comment by susobaco** [comment]
Same problem, Debian 12 
Nextcloud 28.0.5 
OnlyOffice 9.2.0 
Comunity Document Server 0.1.17

**Comment by zsiga19** [comment]
Same problem, docker container
Nextcloud 29.0.4
Community Document Server 0.1.18

**Comment by nemihome** [comment]
Same here with Nextcloud 30.04 and latest app versions
