### ISSUE TITLE
Не удается выполнить sudo -u www-data php occ documentserver:fonts --rebuild

### ISSUE THREAD

**Issue by DeepCollors** [nextcloud/documentserver_community#301]
sudo -u www-data php occ documentserver:fonts --rebuild
rebuilding
Segmentation fault (core dumped)

An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\Fonts::execute()" must be of the type int, "null" returned. in /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/html/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#5 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/html/nextcloud/occ(11): require_once('...')

в веб журнале тоже кучу ошибок сыпет

<html>
<body>

Ошибка | documentserver_community | OCP\Files\NotFoundException: /appdata_oc082m8ktac6/documentserver_community/doc_1077934687/owner/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 139:OC\Files\Node\Root->get()/var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php - line 75:OC\Files\Node\Folder->get()/var/www/html/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 137:OC\Files\SimpleFS\SimpleFolder->getFile()/var/www/html/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php - line 58:OCA\DocumentServer\Document\DocumentStore->saveChanges()/var/www/html/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php - line 71:OCA\DocumentServer\Document\SaveHandler->flushChanges()/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php - line 86:OCA\DocumentServer\BackgroundJob\Cleanup->run()/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php - line 67:OCP\BackgroundJob\Job->start()/var/www/html/nextcloud/cron.php - line 152:OCP\BackgroundJob\Job->execute()
-- | -- | --

</body>
</html>

**Comment by Albirew** [comment]
duplicate of #296
