### ISSUE TITLE
Error When 'occ documentserver:flush'

### ISSUE THREAD

**Issue by bpruneau** [nextcloud/documentserver_community#326]
```
$ php occ documentserver:flush
An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\FlushChanges::execute()" must be of the type int, "null" returned. in /home/itzvfozw/public_html/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /home/itzvfozw/public_html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/itzvfozw/public_html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/itzvfozw/public_html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\DocumentServer\Command\FlushChanges), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/itzvfozw/public_html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/itzvfozw/public_html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/itzvfozw/public_html/console.php(100): OC\Console\Application->run()
#6 /home/itzvfozw/public_html/occ(11): require_once('/home/itzvfozw/...')

$ php -v
PHP 8.1.28 (cli) (built: Apr 18 2024 08:52:48) (NTS)
```

**Comment by bpruneau** [comment]
I had lots of errors in my log file and I think it is related:
![image](https://github.com/nextcloud/documentserver_community/assets/1107683/7ad62862-b9e1-4113-8394-dc3b29430119)

**Comment by son-of-a-door-mat** [comment]
the same error

# sudo -u www-data php occ documentserver:flush
An unhandled exception has been thrown:
TypeError: Return value of "OCA\DocumentServer\Command\FlushChanges::execute()" must be of the type int, "null" returned. in /var/www/netcloud/3rdparty/symfony/console/Command/Command.php:301
Stack trace:
#0 /var/www/netcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#1 /var/www/netcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#2 /var/www/netcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/netcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#4 /var/www/netcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#5 /var/www/netcloud/console.php(102): OC\Console\Application->run()
#6 /var/www/netcloud/occ(11): require_once('...')
#7 {main}root@nextcloud-app:/var/www/netcloud

**Comment by SebastianUnterscheutz** [comment]
Push
